### ISSUE TITLE
 Техническое сообщение повторяется

### ISSUE THREAD

**Issue by ghost** [Dantara/echo-bot#2]
После того как я запускаю `/repeat` и выбираю число *n*, сообщение
```
Current repetitions amount is 3
What amount of repetitions do you prefer?
```
Возвращается *n* раз

**Comment by Dantara** [comment]
Да, в целом так было и задумано. В техническом задании точно об этом ничего не сказано, но хорошо, исправлю

**Comment by Dantara** [comment]
@vladwix, взгляните: #4
